on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  tst:
    uses: theblockbrain/workflows/.github/workflows/gitflow.yml@feat/PDEV-1745
    with:
      container-name: sentimentanalysis
      environment: tst
      branch: main
    secrets:
      iam-role: arn:aws:iam::853310098537:role/github-ecr
